Algoritmo "Faça um algoritmo que receba 2 números e mostre o maior"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Alle Palmeira
// Data atual  : 16/02/2019
Var
   // Seção de Declarações das variáveis
   n1,n2:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o primeiro número: ")
   leia(n1)
   escreva("Digite o segundo número: ")
   leia(n2)



Fimalgoritmo