Algoritmo "Escreva um algoritmo que receba um número
"e mostre a sua metade somente quando ela
"for maior que cinquenta.

// Disciplina  : Lógica de Programação
// Professor   : Alessandro Palmeira
// Professor   : Alle Palmeira
// Data atual  : 16/02/2019
Var
   // Seção de Declarações das variáveis
   n1:real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um número: ")
   leia(n1)


Fimalgoritmo