Algoritmo "AULA05 - Atividade 04"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Alessandro Palmeira
// Descrição   : 4. Escrever um algoritmo que lê um número desconhecido de 0 a 100 e informe em qual intervalo ele se encaixa: [0,25], [26,50], [51,75], [76,100].
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/02/2019
Var
   // Seção de Declarações das variáveis


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo