Algoritmo "semnome"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Alessandro Palmeira
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nicolas A. Santos
// Data atual  : 04/11/2019
Var
   // Seção de Declarações das variáveis
   c,n:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreva("Digite um número: ")
   leia(n)

   para c de 1 ate n faca
      escreval(c)
   fimpara
Fimalgoritmo